" Show line numbers
set number

" Highlight matching brace
set showmatch

" vim-taglist
let Tlist_Compact_Format = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
nnoremap <C-l> :TlistToggle<CR>

" Use mouse
set mouse=a

" Filetype detection
filetype plugin on
syntax on


