# Zsh Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


# Powerline

export TERM="xterm-256color"
POWERLEVEL9K_MODE='awesome-fontconfig'

source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme


# Aliases

if [[ -f $HOME/.aliases ]]; then
	. $HOME/.aliases
fi



