# Zsh Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


# Powerline

export TERM="xterm-256color"
POWERLEVEL9K_MODE='awesome-fontconfig'

source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme


# Aliases

if [[ -f $HOME/.aliases ]]; then
	. $HOME/.aliases
fi

# Scripts

export PATH=${PATH}:${HOME}/.local/bin


# Bitbake

export PATH=${PATH}:$HOME/.bitbake/bin
export PYTHONPATH=$HOME/.bitbake/lib


# Most terminal emulators (ie. xterm, rxvt, PuTTY, etc) default to intercepting CTRL+S to suspend output
# (CTRL+Q unsuspends if you're wondering), if so you will need to disable this behaviour to use novim-mode's ,
# shortcuts for saving and quitting. Most often you simply need to add the following to your ~/.bashrc, ~/.zshrc or similar:
stty -ixon
stty stop undef
